const actions = {
    ADD_SYMBOL_TO_PORTFOLIO: "ADD_SYMBOL_TO_PORTFOLIO",
    REMOVE_SYMBOL_FROM_PORTFOLIO: "REMOVE_SYMBOL_FROM_PORTFOLIO",
    TOGGLE_SYMBOL_MASTER_DETAIL: "TOGGLE_SYMBOL_MASTER_DETAIL",
    UPDATE_SYMBOL_PRICE: "UPDATE_SYMBOL_PRICE",
    SET_SYMBOLS: "SET_SYMBOLS"
}

export default actions;